version: "3.8"
services:
  permissions-service:
    container_name: permissions-service
    build:
      context: .
      dockerfile: permissions/Dockerfile
    volumes:
      - ./permissions:/permissions
    ports:
      - 50051:50051
    env_file:
      - .env
    command: python main.py
    networks:
      - microservices
    depends_on:
      - permissions-database

  permissions-database:
    container_name: permissions-database
    networks:
      - microservices
    image: postgres
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    volumes:
      - permissions-database:/var/lib/postgresql/data
      - ./permissions/init.sql:/docker-entrypoint-initdb.d/init.sql
    hostname: ${DATABASE_HOST}
    env_file:
      - .env

  insights-service:
    container_name: insights-service
    build:
      context: .
      dockerfile: insights/Dockerfile
    volumes:
      - ./insights:/insights
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - microservices

volumes:
  permissions-database:
networks:
  microservices: