version: "3.8"
services:
  permissions:
    container_name: permissions
    build:
      context: .
      dockerfile: permissions/Dockerfile
    volumes:
      - ./permissions:/permissions
    ports:
      - 50051:50051
    command: python main.py
    networks:
      - microservices
    depends_on:
      - permissions-database

  insights:
    container_name: insights
    build:
      context: .
      dockerfile: insights/Dockerfile
    volumes:
      - ./insights:/insights
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - microservices
  permissions-database:
    container_name: permissions-database
    networks:
      - microservices
    image: postgres
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    command: -p ${DATABASE_PORT}
    volumes:
      - permissions-database:/var/lib/postgresql/data
      - ./init.sql:/init.sql
    hostname: ${DATABASE_HOST}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DATABASE}
      - POSTGRES_PORT=${DATABASE_PORT}
    env_file:
      - .env

volumes:
  permissions-database:
networks:
  microservices: